export const musicOption = [
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "love is a way to lie to your selfto lie to your selfto lie to your self",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
  {
    songName: "baba nla",
    artist: "wizkid",
    album: "ayo",
    year: "2015",
    genre: "afrobeat",
    time: "1:11",
  },
];
